name: Pull Request Details
on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  print_details:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Print Pull Request Details
        run: |
          echo "Hello World"
          echo "Autor: ${{ github.event.pull_request.user.login }}"
          echo "Ultimo commit: ${{ github.event.pull_request.head.sha }}"
          echo "Cambios entre el último commit y la rama principal (default branch):"
          git diff --name-only ${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }}
